language : node_js
node_js :
- stable
services:
- postgresql
before_script:
- psql -c "create database free_mentors;" -U postgres
script :
- npm run seeder
- npm run test -s
after_success:
- npm run coverage
